version: '3.8'

services:
  node-app:
    image: starteja007/node-app:1.0.1
    ports:
      - 3000:3000
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD:my-pwd
 